### ISSUE TITLE
Request: Appsflyer one links

### ISSUE THREAD

**Issue by DarwinVJ** [la-haus/flutter-segment#41]
Does the plugin have onelinks configuration or must the appsflyer plugin be installed to detect onelinks?

**Comment by danielgomezrico** [comment]
This is the PR that added appsflyer integration https://github.com/la-haus/flutter-segment/pull/19

You are welcome to create a contribution with that too :)

**Comment by brightmind-loredo** [comment]
Be careful... Onelinks are useful in (at least) two different use cases: 1) user attribution and 2) deep linking (Appsflyer defines this term).  This 2nd use case is well beyond the scope of Segment.io Identify and Track calls, but super useful for marketing your app.  So to the extent you will need deep linking you will need to integrate your app with Appsflyer SDK.  I just did this and it was not very painful especially because AF has excellent customer support.

**Comment by danielgomezrico** [comment]
@DarwinVJ why did you close this?

**Comment by DarwinVJ** [comment]
> @DarwinVJ why did you close this?

I thought that this topic was already closed with the answers you gave.

**Comment by danielgomezrico** [comment]
Darwin just to confirm, it already detects one links?

**Comment by DarwinVJ** [comment]
> 

Yes, using only appsflyer sdk to listen to onelinks

**Comment by danielgomezrico** [comment]
Then yeah, this issue could be closed :)
